[workspace]
members = ["internal", "derive", "public"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Morgan Welsch <welschmorgan@gmail.com>"]
description = "A rust tookit to deal with bureaucratic struct implementations"
