[package]
name = "pod-internal"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Bureaucratic structs to speed up rust development"

[lib]
name = "pod_internal"

[dependencies]
